exclude:
- README.md
title: Amirhossein's homepage
description: >- # A short description of your site
  I write about mathematics here!
theme: jekyll-theme-minima

plugins:
  - jekyll-feed
 - jekyll-seo-tag

author:
  name: Amirhossein Shaker
  email: shaker.amir.h@gmail.com
