exclude:
- README.md
title: Amirhossein's homepage
description: >- # A short description of your site
  I write about mathematics here!
theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
minima:
  skin: dark
author:
  #name: John Smith
  email: "john.smith@foobar.com"
